import React from 'react';
import GatewaySetup from './GatewaySetup';
import { CONTROL_STEPS } from '../../services/plantops/controlWorkflow';
import { connectorCapabilities } from '../../services/plantops/MockScadaAdapter';
import { usePlantOps } from '../../hooks/usePlantOps';
import './PlantOpsDashboard.css';

const modes = ['Read Only', 'Copilot', 'Supervised', 'Constrained Control'];
const fmt = (number, digits = 1) => Number(number || 0).toFixed(digits);
const MiniTrend = ({ color = '#0e7490' }) => <svg className="po-trend" viewBox="0 0 120 34" aria-hidden="true"><path d="M2 27 C16 24 18 12 32 17 S49 30 62 19 80 7 91 14 105 22 118 6" fill="none" stroke={color} strokeWidth="2.5"/><path d="M2 27 C16 24 18 12 32 17 S49 30 62 19 80 7 91 14 105 22 118 6 V34 H2Z" fill={color} opacity=".08"/></svg>;

function KpiCard({ label, value, unit, detail, tone }) { return <article className={`po-kpi ${tone || ''}`}><div><span>{label}</span><b>{value}<small>{unit}</small></b><em>{detail}</em></div><MiniTrend color={tone === 'green' ? '#059669' : tone === 'amber' ? '#d97706' : '#0e7490'} /></article>; }

function ProcessFlow({ twin }) { return <section className="po-card po-process"><header><div><span className="po-eyebrow">Live process model</span><h2>Detected MVR evaporation train</h2></div><span className="po-confidence">{twin?.confidence || 0}% match</span></header><div className="po-flow" aria-label="MVR process flow"><div className="po-feed"><i />Feed<br/><b>12.8 t/h</b></div><div className="po-line" /><div className="po-unit"><span>V-201</span><b>Evaporator</b><small>−0.82 bar(g)</small></div><div className="po-loop"><span className="po-compressor">C-401<br/><b>MVR</b></span><span className="po-calandria">E-201<br/><b>Calandria</b></span></div><div className="po-line" /><div className="po-product"><i />Product<br/><b>47.8% w/w</b></div></div><footer>{twin?.equipment.map(item => <span key={item.id}><i className={item.health < 86 ? 'watch' : ''}/>{item.id} {item.name}<b>{item.health}%</b></span>)}</footer></section>; }

export default function PlantOpsDashboard() {
  const { connection, snapshot, twin, recommendations, mode, setMode, activeStep, audit, busy, approve } = usePlantOps();
  const k = twin?.kpis || {};
  return <main className="plantops-shell">
    <GatewaySetup />
    <div className="po-topbar"><div><span className="po-mark">EDG</span><div><p>EngineeringDrawing.io</p><h1>PlantOps <sup>AI</sup></h1></div></div><div className="po-site"><span><i className={connection.connected ? '' : 'offline'}/> {connection.connected ? 'Plant connected' : 'Connecting…'}</span><b>MVR Demo Plant · Line 01</b></div></div>
    <div className="po-safety"><span>SIMULATION ENVIRONMENT</span><p>Read-only plant data · PLC/DCS/SIS protections remain authoritative · Real actuator writes disabled</p><b>Manual fallback ready</b></div>
    <nav className="po-modes" aria-label="Operating mode">{modes.map(item => <button key={item} className={mode === item ? 'active' : ''} disabled={item === 'Constrained Control' || item === 'Supervised'} onClick={() => setMode(item)}><i />{item}{item === 'Supervised' && <small>Simulation only</small>}{item === 'Constrained Control' && <small>Locked</small>}</button>)}</nav>
    <section className="po-status-row"><div><span className="po-eyebrow">SCADA source</span><b>{connection.source || 'Discovering…'}</b><small>{connection.protocol} · {connection.latency} ms · Read only</small></div><div><span className="po-eyebrow">Live tags</span><b>{snapshot ? Object.keys(snapshot.tags).length : 0} / 12</b><small>Good quality · 2.2 s refresh</small></div><div><span className="po-eyebrow">Process recognition</span><b>{twin?.process || 'Analyzing process…'}</b><small>4 equipment units mapped</small></div><div><span className="po-eyebrow">Operating state</span><b>Stable production</b><small><i className="po-pulse"/> AI monitoring continuously</small></div></section>
    <section className="po-kpis"><KpiCard label="Evaporation rate" value={fmt(k.evaporationRate, 2)} unit="t/h" detail="+1.2% vs last hour" tone="green"/><KpiCard label="Specific energy" value={fmt(k.specificEnergy)} unit="kWh/t" detail="12 kWh/t above target" tone="amber"/><KpiCard label="Product quality" value={fmt(k.concentration)} unit="% w/w" detail="Target 48.0 ± 0.5" tone="green"/><KpiCard label="Production efficiency" value={fmt(k.productionEfficiency)} unit="%" detail="Stable · capacity available"/></section>
    <div className="po-main-grid"><ProcessFlow twin={twin}/><aside className="po-card po-copilot"><header><div><span className="po-ai-dot">✦</span><div><span className="po-eyebrow">EDG AI copilot</span><h2>Plant brief</h2></div></div><span>Live</span></header><div className="po-ai-summary"><b>The plant is stable, with one efficiency opportunity.</b><p>Evaporation is holding near 8.4 t/h and product concentration is on target. Energy use increased as heat-transfer performance softened, consistent with early fouling.</p></div><dl><div><dt>Why it changed</dt><dd>U-value is 13% below clean baseline while vacuum and feed conditions remain stable.</dd></div><div><dt>What to tune</dt><dd>Trial a bounded +6 m³/h circulation increase in simulation.</dd></div><div><dt>Expected impact</dt><dd>Recover 1.8–2.4% evaporation and reduce SEC by ~12 kWh/t.</dd></div></dl><div className="po-ai-confidence"><span>Model confidence</span><b>87%</b><i><em style={{width:'87%'}}/></i></div></aside></div>
    <div className="po-lower-grid"><section className="po-card po-recommend"><header><div><span className="po-eyebrow">Optimization queue</span><h2>Recommended action</h2></div><span className="po-opportunity">Efficiency opportunity</span></header>{recommendations.map(rec => <div key={rec.id}><h3>{rec.issue}</h3><p>{rec.evidence}</p><div className="po-target"><span>Suggested target<b>{rec.suggestedTarget}</b></span><span>Expected benefit<b>{rec.expectedBenefit}</b></span></div><div className="po-constraints"><b>Safety envelope</b>{rec.safetyConstraints.map(item => <span key={item}>✓ {item}</span>)}<small>Rollback: {rec.rollbackCondition}</small></div><button disabled={busy || mode === 'Read Only'} onClick={() => approve(rec)}>{busy ? `${activeStep}…` : mode === 'Read Only' ? 'Switch to Copilot to review' : 'Approve simulated trial'} <span>→</span></button></div>)}</section><section className="po-card po-control"><header><div><span className="po-eyebrow">Safe control workflow</span><h2>Approval & verification</h2></div><span>Simulation only</span></header><ol>{CONTROL_STEPS.map((step, index) => <li key={step} className={CONTROL_STEPS.indexOf(activeStep) >= index ? 'done' : ''}><i>{index + 1}</i><span>{step}<small>{index === 0 ? '12 live tags validated' : index === 1 ? 'Constraints checked' : index === 2 ? 'Named operator gate' : index === 3 ? 'No real write path' : index === 4 ? 'Twin response check' : 'Immutable event record'}</small></span></li>)}</ol></section></div>
    <div className="po-bottom-grid"><section className="po-card po-alarms"><header><div><span className="po-eyebrow">Alarms & events</span><h2>Operations watch</h2></div><span>0 critical</span></header><div><b className="advisory">Advisory</b><span>Heat-transfer performance below clean baseline<small>10:42 · CALC-U01</small></span></div><div><b className="normal">Normal</b><span>Product concentration within quality band<small>10:41 · AIT-501</small></span></div></section><section className="po-card po-audit"><header><div><span className="po-eyebrow">Audit trail</span><h2>Recent decisions</h2></div><span>Export ready</span></header>{audit.map((item, i) => <div key={`${item.time}-${i}`}><i>✓</i><span>{item.event}<small>{item.actor} · {new Date(item.time).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', second:'2-digit'})}</small></span></div>)}</section><section className="po-card po-connectors"><span className="po-eyebrow">Connector architecture</span><h2>Ready for plant interfaces</h2><div>{connectorCapabilities.map((item, i) => <span className={i === 0 ? 'ready' : ''} key={item}>{item}<small>{i === 0 ? 'Simulated' : 'Adapter ready'}</small></span>)}</div><p>Real write service is not configured.</p></section></div>
  </main>;
}
