import React,{useEffect,useMemo,useRef,useState} from "react";
import {BrowserProvider,Contract,parseUnits} from "ethers";
import DistillationHMBD from "./DistillationHMBD";
import DistillationPlant3D from "./DistillationPlant3D";
import {createDistillationPackage} from "./downloadPackage";
import {calculateDistillationDesign,DISTILLATION_DEFAULTS,DISTILLATION_SYSTEMS} from "./distillationDesignEngine";
import {openShoplineCheckout,shoplineCheckoutEnabled} from "../payments/shoplineCheckout";
import tokenMeta from "../../EnggDrawTokenABI.json";
import "./DistillationProduction.css";

const configuredApiBase=process.env.REACT_APP_API_BASE_URL||"";
const API_BASE=/^https?:\/\//.test(configuredApiBase)&&!configuredApiBase.includes("localhost")?configuredApiBase.replace(/\/$/,""):"";
const EDG_ADMIN_WALLET="0xD9738cc53E9746a01cAC8EF01aF17fF4e88DD25F";
const EDG_ABI=["function balanceOf(address) view returns (uint256)","function transfer(address,uint256) returns (bool)"];
const format=value=>Number(value||0).toLocaleString("en-US",{maximumFractionDigits:2});

export default function DistillationProduction(){
  const [inputs,setInputs]=useState(DISTILLATION_DEFAULTS);
  const [tab,setTab]=useState("pfd");
  const [payment,setPayment]=useState("BNB");
  const [paymentStatus,setPaymentStatus]=useState(localStorage.getItem("distillationPackagePaid")?"paid":"idle");
  const [message,setMessage]=useState("");
  const pfdRef=useRef(null);
  const design=useMemo(()=>calculateDistillationDesign(inputs),[inputs]);
  const shoplineEnabled=shoplineCheckoutEnabled("distillation");
  const update=(key,value)=>{setInputs(current=>({...current,[key]:value}));setTab("pfd");setMessage("");};
  const reset=()=>{setInputs(DISTILLATION_DEFAULTS);setTab("pfd");setMessage("");};

  useEffect(()=>{
    const query=new URLSearchParams(window.location.search),result=query.get("payment"),order=query.get("order")||localStorage.getItem("distillationPaymentOrder");
    if(result==="cancelled"){setMessage("Payment cancelled; your simulation is preserved.");window.history.replaceState({},"",window.location.pathname);return undefined;}
    if(result!=="return"||!order)return undefined;
    setPaymentStatus("pending");setMessage("Checking secure payment status...");let stopped=false,attempts=0;
    const check=async()=>{attempts+=1;try{const response=await fetch(`${API_BASE}/api/payments/nowpayments/status/${encodeURIComponent(order)}`),body=await response.json();if(!response.ok)throw new Error(body.error);if(body.status==="finished"){localStorage.setItem("distillationPackagePaid",`NOWPAYMENTS-${order}`);setPaymentStatus("paid");setMessage("Payment confirmed. Professional distillation BEP unlocked.");window.history.replaceState({},"",window.location.pathname);return;}if(["failed","expired","refunded"].includes(body.status)){setPaymentStatus("idle");setMessage(`Payment ${body.status}. Please create a new checkout.`);return;}if(!stopped&&attempts<30)window.setTimeout(check,4000);}catch(error){setPaymentStatus("idle");setMessage(error.message||"Could not verify payment.");}};
    check();return()=>{stopped=true;};
  },[]);

  async function startBnb(){
    setPaymentStatus("pending");setMessage("");
    try{const response=await fetch(`${API_BASE}/api/payments/nowpayments/distillation/invoice`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({design:{feedFlow:design.F,system:design.inputs.system}})}),body=await response.json();if(!response.ok||!body.invoiceUrl)throw new Error(body.error||"Could not create checkout.");localStorage.setItem("distillationPaymentOrder",body.orderId);window.location.assign(body.invoiceUrl);}catch(error){setPaymentStatus("idle");setMessage(error.message||"Could not open secure BNB checkout.");}
  }
  async function payEdg(){
    if(!window.ethereum){setMessage("Install MetaMask or open this page in its wallet browser.");return;}setPaymentStatus("pending");setMessage("");
    try{await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x38"}]});const provider=new BrowserProvider(window.ethereum),signer=await provider.getSigner(),buyer=await signer.getAddress(),token=new Contract(tokenMeta.ADDRESS,EDG_ABI,signer),amount=parseUnits("5000",18);const [balance,gas]=await Promise.all([token.balanceOf(buyer),provider.getBalance(buyer)]);if(balance<amount)throw new Error("This wallet needs at least 5,000 transferable EDG.");if(gas===0n)throw new Error("Add a small amount of BNB for the network fee.");const transaction=await token.transfer(EDG_ADMIN_WALLET,amount);setMessage("Waiting for BNB Smart Chain confirmation...");const receipt=await transaction.wait();if(!receipt||receipt.status!==1)throw new Error("Transfer was not confirmed.");localStorage.setItem("distillationPackagePaid",`EDG-${transaction.hash}`);setPaymentStatus("paid");setMessage("5,000 EDG confirmed. Professional distillation BEP unlocked.");}catch(error){setPaymentStatus("idle");setMessage(error.shortMessage||error.reason||error.message||"Payment cancelled.");}
  }
  function payShopline(){setMessage("");try{openShoplineCheckout("distillation");}catch(error){setMessage(error.message);}}
  function downloadPackage(){const svgNode=pfdRef.current?.querySelector("svg"),svg=svgNode?new XMLSerializer().serializeToString(svgNode):"<svg xmlns='http://www.w3.org/2000/svg'/>",blob=createDistillationPackage(design.inputs,design,svg),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`engineering-drawing-${design.inputs.system.toLowerCase().replace(/[^a-z]+/g,"-")}-distillation-bep.zip`;link.click();URL.revokeObjectURL(url);}

  return <main className="dsp-page">
    <section className="dsp-hero">
      <div className="dsp-copy"><span className="dsp-kicker">INDUSTRIAL SEPARATION ENGINEERING · LIVE DESIGN</span><h1>Industrial distillation column design simulator</h1><p>Enter a feed basis and product purities to estimate the material balance, minimum stages, reflux, column diameter and height, condenser and reboiler duties, utilities, CAPEX and capacity-responsive 3D plant arrangement.</p><div className="dsp-flow"><span><b>01</b> Feed basis</span><span><b>02</b> Review separation</span><span><b>03</b> Download BEP</span></div></div>
      <div className="dsp-input-card"><div className="dsp-card-head"><div><small>COMMERCIAL CONCEPT DESIGN</small><h2>Separation basis</h2></div><button onClick={reset}>Reset</button></div>
        <div className="dsp-primary">
          <label>SYSTEM<select value={inputs.system} onChange={event=>update("system",event.target.value)}>{DISTILLATION_SYSTEMS.map(system=><option key={system}>{system}</option>)}</select><small>Screening property pack; confirm rigorous VLE before design freeze</small></label>
          <Field label="FEED FLOW" value={inputs.feedFlow} unit="kmol/h" min={1} max={5000} step={1} onChange={value=>update("feedFlow",value)}/>
          <Field label="LIGHT KEY IN FEED" value={inputs.zF} unit="mol frac" min={.01} max={.99} step={.01} onChange={value=>update("zF",value)}/>
          <Field label="DISTILLATE PURITY" value={inputs.xD} unit="LK mol frac" min={Math.min(.98,Number(inputs.zF)+.01)} max={.995} step={.005} onChange={value=>update("xD",value)}/>
          <Field label="BOTTOMS PURITY" value={inputs.xB} unit="LK mol frac" min={.001} max={Math.max(.01,Number(inputs.zF)-.01)} step={.005} onChange={value=>update("xB",value)}/>
        </div>
        <details className="dsp-advanced"><summary>Engineering assumptions <span>Optional · updates live</span></summary><div>
          <Field label="Relative volatility" value={inputs.alpha} unit="α" min={1.05} max={10} step={.05} onChange={value=>update("alpha",value)}/><Field label="Feed quality" value={inputs.q} unit="q" min={0} max={1.2} step={.05} onChange={value=>update("q",value)}/><Field label="Reflux factor" value={inputs.refluxFactor} unit="R/Rmin" min={1.05} max={3} step={.05} onChange={value=>update("refluxFactor",value)}/><label>INTERNALS<select value={inputs.internals} onChange={event=>update("internals",event.target.value)}><option value="trays">Valve trays</option><option value="packing">Structured packing</option></select></label><Field label="Top pressure" value={inputs.pressureTopKpa} unit="kPa(a)" min={20} max={500} step={1} onChange={value=>update("pressureTopKpa",value)}/><Field label="Tray efficiency" value={inputs.efficiency} unit="fraction" min={.35} max={.9} step={.01} onChange={value=>update("efficiency",value)}/><Field label="Design flood" value={inputs.floodFraction} unit="fraction" min={.5} max={.9} step={.01} onChange={value=>update("floodFraction",value)}/><label>MATERIAL<select value={inputs.moc} onChange={event=>update("moc",event.target.value)}><option>SS316L</option><option>SS304</option><option>Carbon Steel</option><option>Duplex 2205</option></select></label>
        </div></details>
        <div className="dsp-live"><span><i/> LIVE SIMULATION</span><b>{format(design.D)} kmol/h distillate · {format(design.B)} kmol/h bottoms</b><small>Balance closure {design.closure} kmol/h · {format(design.Qr_kJph/3600)} kW reboiler duty</small></div>
      </div>
    </section>

    <section className="dsp-results"><div className="dsp-summary"><div><span className="dsp-kicker">PRELIMINARY BASIC ENGINEERING</span><h2>{design.inputs.system} distillation system</h2><p>{format(design.F)} kmol/h feed · {format(design.D)} kmol/h distillate · {design.inputs.internals}</p></div><div className="dsp-kpis"><Kpi name="COLUMN ID" value={design.Dcol} unit="m"/><Kpi name="TOTAL HEIGHT" value={design.Hcol} unit="m"/><Kpi name="ACTUAL STAGES" value={design.Nactual||"—"} unit={design.inputs.internals}/><Kpi name="CONDENSER" value={format(design.Qc_kJph/3600)} unit="kW"/><Kpi name="REBOILER" value={format(design.Qr_kJph/3600)} unit="kW"/><Kpi name="CAPEX" value={`$${format(design.installedUsd)}`} unit="Class 4"/></div></div>
      <div className="dsp-tabs">{[["pfd","PFD + HMBD",false],["3d","3D plant",false],["cost","Budget estimate",false],["operation","Operating overview",true],["equipment","Equipment schedule",true],["lines","Lines & valves",true]].map(([key,label,locked])=><button key={key} className={`${tab===key?"active":""} ${locked?"locked":""}`} onClick={()=>setTab(key)}>{locked&&<span>🔒</span>}{label}</button>)}</div>
      <div className="dsp-workspace"><div className="dsp-main">
        {tab==="pfd"&&<section className="dsp-pfd" ref={pfdRef}><header><div><small>ED-DS-PFD-001 · REV 00</small><b>Live process flow diagram and heat &amp; mass balance</b></div><span>{design.inputs.system} · {format(design.F)} kmol/h</span></header><div className="dsp-balance"><Balance name="S-01 FEED" value={`${format(design.F)} kmol/h`} note={`zLK ${design.zF}`}/><Balance name="S-03 DISTILLATE" value={`${format(design.D)} kmol/h`} note={`xLK ${design.xD}`}/><Balance name="S-05 BOTTOMS" value={`${format(design.B)} kmol/h`} note={`xLK ${design.xB}`}/><Balance name="CONDENSER" value={`${format(design.Qc_kJph/3600)} kW`} note={`${design.Ttop} °C top`}/><Balance name="REBOILER" value={`${format(design.Qr_kJph/3600)} kW`} note={`${design.Tbot} °C bottom`}/><Balance name="CLOSURE" value={`${design.closure} kmol/h`} note={`${format(design.F)} = ${format(design.D)} + ${format(design.B)}`}/></div><DistillationHMBD data={design}/></section>}
        {tab==="3d"&&<DistillationPlant3D data={design} inputs={design.inputs}/>} {tab==="cost"&&<CostPanel design={design}/>} {["operation","equipment","lines"].includes(tab)&&<LockedPanel title={tab==="operation"?"Operating overview":tab==="equipment"?"Equipment schedule":"Line and valve schedules"}/>} {tab!=="pfd"&&<div className="dsp-hidden"><DistillationHMBD data={design}/></div>}
      </div><PackageCard payment={payment} setPayment={setPayment} status={paymentStatus} message={message} startBnb={startBnb} payEdg={payEdg} payShopline={payShopline} shoplineEnabled={shoplineEnabled} download={downloadPackage}/></div>
      <div className="dsp-warnings">{design.warnings.length?design.warnings.map(item=><p key={item}>⚠ {item}</p>):<p className="ok">✓ The inputs are within the preliminary shortcut-design envelope. Confirm rigorous thermodynamics and hydraulic rating before vendor issue.</p>}</div>
      <section className="dsp-review"><div><span>AI-ASSISTED ENGINEERING REVIEW</span><b>Calculation-led design check</b></div><ul><li>Overall balance closes at {design.closure} kmol/h for the current feed and purity basis.</li><li>{design.Nactual||"—"} actual {design.inputs.internals==="trays"?"trays":"equivalent stages"} are indicated at {Math.round(design.effMV*100)}% efficiency.</li><li>Estimated utilities are {format(design.mCW_kgph)} kg/h cooling water and {format(design.mSteam)} kg/h steam.</li></ul></section>
    </section>
    <section className="dsp-seo"><span className="dsp-kicker">DISTILLATION COLUMN ENGINEERING</span><h2>A practical feed-to-plant workflow for early separation design</h2><p>Use a consistent binary feed basis to screen material balance, reflux, stage count, column hydraulics, heat exchangers, utilities and plant arrangement before committing to detailed simulation.</p><div><article><h3>Feed and product basis</h3><p>Material balance and purity specifications update together so every PFD, KPI and downloaded file uses the same design case.</p></article><article><h3>PFD and CAD-style 3D concept</h3><p>Review the column, condenser, reflux drum, reboiler, pumps, product tanks, pipe routing and access envelope in one workflow.</p></article><article><h3>Controlled professional package</h3><p>Purchase branded engineering schedules through BNB, EDG, or SHOPLINE hosted checkout when configured.</p></article></div></section>
  </main>;
}

function Field({label,value,unit,min,max,step,onChange}){const enforce=event=>onChange(Math.min(max,Math.max(min,Number(event.target.value)||min)));return <label>{label}<span><input type="number" value={value} min={min} max={max} step={step} onChange={event=>onChange(event.target.value)} onBlur={enforce}/>{unit}</span><small>{min}–{max}</small></label>}
function Kpi({name,value,unit}){return <span><small>{name}</small><b>{value}</b><em>{unit}</em></span>}
function Balance({name,value,note}){return <article><small>{name}</small><b>{value}</b><span>{note}</span></article>}
function LockedPanel({title}){return <section className="dsp-locked"><span>🔒</span><small>PROFESSIONAL BASIC ENGINEERING PACKAGE</small><h3>{title}</h3><p>Detailed tagged schedules are included in the paid package and are not exposed in the public simulator.</p><div>{[1,2,3,4,5].map(value=><i key={value}/>)}</div></section>}
function CostPanel({design}){const rows=[["Column shell and internals",.31],["Condenser, reboiler and drum",.25],["Pumps, piping and valves",.14],["Instrumentation and electrical",.12],["Structure, installation and engineering",.18]];return <section className="dsp-cost"><div><small>PRELIMINARY INSTALLED CAPEX</small><b>${format(design.installedUsd)}</b><span>₹{format(design.installedInr)}</span></div><ul>{rows.map(([name,share])=><li key={name}><span>{name}</span><b>${format(design.installedUsd*share)}</b></li>)}</ul><p><b>Class 4 screening estimate.</b> Excludes land, taxes, buildings, major offsites, solvent recovery studies, validation and statutory fees.</p></section>}
function PackageCard({payment,setPayment,status,message,startBnb,payEdg,payShopline,shoplineEnabled,download}){const action=payment==="EDG"?payEdg:payment==="SHOPLINE"?payShopline:startBnb,cta=payment==="EDG"?"Pay 5,000 EDG with MetaMask":payment==="SHOPLINE"?"Continue to SHOPLINE checkout":"Pay securely with BNB · $100";return <aside className="dsp-package"><small>PROFESSIONAL BEP · SECURE CHECKOUT</small><h3>Complete distillation engineering package</h3><ul><li>Controlled branded design report</li><li>Professional calculation workbook</li><li>Stream heat and mass balance</li><li>Equipment, line and valve schedules</li><li>PFD SVG, 3D OBJ and design JSON</li><li>Class 4 cost estimate</li></ul><div className={`dsp-payments ${shoplineEnabled?"has-shopline":""}`}><button className={payment==="BNB"?"active":""} onClick={()=>setPayment("BNB")}><i className="bnb">◆</i><b>BNB</b><em>$100 equivalent</em></button><button className={payment==="EDG"?"active":""} onClick={()=>setPayment("EDG")}><i><img src="/assets/edg_logo.svg" alt="EDG"/></i><b>EDG</b><em>5,000 EDG</em></button>{shoplineEnabled&&<button className={payment==="SHOPLINE"?"active":""} onClick={()=>setPayment("SHOPLINE")}><i className="shopline">S</i><b>Card</b><em>SHOPLINE</em></button>}</div><div className="dsp-price"><span>Production distillation BEP</span><b>{payment==="EDG"?"5,000 EDG":"$100 USD"}</b><em>{payment==="EDG"?"Direct EDG transfer on BNB Smart Chain":payment==="SHOPLINE"?"Secure hosted checkout by SHOPLINE":"BNB on BSC · NOWPayments checkout"}</em></div>{status==="paid"?<button className="dsp-buy" onClick={download}>Download professional BEP ↓</button>:<button className="dsp-buy" disabled={status==="pending"} onClick={action}>{status==="pending"?"Confirming payment...":cta}</button>}{message&&<p className="dsp-message">{message}</p>}<p className="dsp-safety">Preliminary design only. Final process, mechanical, relief, controls and statutory engineering requires authorized professional review.</p></aside>}
