import { makeZip } from "../evaporator/downloadPackage";
const csv=rows=>rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\r\n");
export function createDistillationPackage(inputs,d,pfdSvg){
  const date=new Date().toISOString().slice(0,10),height=Number(d.Hcol||d.Hpack||0).toFixed(2);
  const report=`<!doctype html><html><head><meta charset="utf-8"><title>Distillation BEP</title><style>body{font:14px Arial;color:#182238;margin:42px}header{border-bottom:5px solid #6847f5;padding-bottom:15px}h1{margin:5px 0}.brand{color:#6847f5;font-weight:900;letter-spacing:.12em}table{width:100%;border-collapse:collapse;margin:18px 0}td,th{border:1px solid #ccd4e0;padding:8px}.warn{background:#fff4d6;border-left:5px solid #d99d16;padding:12px}footer{margin-top:35px;border-top:1px solid #ccd4e0;padding-top:10px;font-size:11px}</style></head><body><header><div class="brand">ENGINEERING DRAWING</div><h1>Industrial Distillation Basic Engineering Package</h1><div>ED-DS-BEP-001 · Rev 00 · ${date}</div></header><h2>${inputs.system}</h2><table><tr><th>Feed</th><td>${d.F.toFixed(2)} kmol/h</td><th>Distillate</th><td>${d.D.toFixed(2)} kmol/h</td></tr><tr><th>Bottoms</th><td>${d.B.toFixed(2)} kmol/h</td><th>Balance closure</th><td>${(d.F-d.D-d.B).toFixed(4)} kmol/h</td></tr><tr><th>Column ID</th><td>${d.Dcol.toFixed(2)} m</td><th>Active height</th><td>${height} m</td></tr><tr><th>Condenser duty</th><td>${(d.Qc_kJph/3600).toFixed(1)} kW</td><th>Reboiler duty</th><td>${(d.Qr_kJph/3600).toFixed(1)} kW</td></tr></table><div class="warn"><b>PRELIMINARY / NOT FOR CONSTRUCTION.</b> Confirm VLE with an appropriate thermodynamic model and laboratory data. Final hydraulics, mechanical design, relief, metallurgy, controls, emissions, HAZOP and statutory review remain project-specific.</div><footer>Engineering Drawing · www.engineeringdrawing.io · Controlled client concept document</footer></body></html>`;
  const balance=[["ENGINEERING DRAWING - DISTILLATION HMBD","",""],["Parameter","Value","Unit"],["Feed",d.F,"kmol/h"],["Feed LK",d.F*d.zF,"kmol/h"],["Distillate",d.D,"kmol/h"],["Bottoms",d.B,"kmol/h"],["Closure",d.F-d.D-d.B,"kmol/h"],["N minimum",d.Nmin,"stages"],["N theoretical",d.Nth,"stages"],["R minimum",d.Rmin,""],["Operating reflux",d.R,""],["Column ID",d.Dcol,"m"],["Active height",d.Hcol||d.Hpack,"m"],["Condenser duty",d.Qc_kJph/3600,"kW"],["Reboiler duty",d.Qr_kJph/3600,"kW"],["CW",d.mCW_kgph,"kg/h"],["Steam",d.mSteam,"kg/h"]];
  const equipment=[["Tag","Equipment","Design basis","MOC"],["C-101","Distillation column",`${d.Dcol.toFixed(2)} m ID x ${height} m active`,inputs.MOC],["E-101","Feed preheater","Vendor thermal rating",inputs.MOC],["E-102","Overhead condenser",`${Number(d.Ac||0).toFixed(2)} m2`,inputs.MOC],["V-101","Reflux drum",`${Number(d.Vdrum||0).toFixed(2)} m3`,inputs.MOC],["E-103","Reboiler",`${Number(d.Ar||0).toFixed(2)} m2`,inputs.MOC],["P-101 A/B","Reflux pumps","1 operating + 1 standby",inputs.MOC],["P-102 A/B","Bottoms pumps","1 operating + 1 standby",inputs.MOC]];
  return makeZip({"00_README.txt":"ENGINEERING DRAWING\nIndustrial distillation preliminary BEP. NOT FOR CONSTRUCTION.","01_Controlled_Report.html":report,"02_PFD_HMBD.svg":pfdSvg,"03_Heat_Mass_Balance.csv":csv(balance),"04_Equipment_Schedule.csv":csv(equipment),"05_Design_Data.json":JSON.stringify({inputs,calculation:d},null,2)});
}
